<?php
namespace Prosperoking\KudaOpenApi;

class ServiceTypes {
    const ADMIN_CREATE_VIRTUAL_ACCOUNT = "ADMIN_CREATE_VIRTUAL_ACCOUNT";
    const RETRIEVE_SINGLE_VIRTUAL_ACCOUNT = "RETRIEVE_SINGLE_VIRTUAL_ACCOUNT";
    const BANK_LIST = "BANK_LIST";
    const NAME_ENQUIRY = "NAME_ENQUIRY";
    const SINGLE_FUND_TRANSFER = "SINGLE_FUND_TRANSFER";
    const VIRTUAL_ACCOUNT_FUND_TRANSFER = "VIRTUAL_ACCOUNT_FUND_TRANSFER";
    const TRANSACTION_STATUS_QUERY = "TRANSACTION_STATUS_QUERY";
    const RETRIEVE_VIRTUAL_ACCOUNT_BALANCE = "RETRIEVE_VIRTUAL_ACCOUNT_BALANCE";
    const ADMIN_MAIN_ACCOUNT_TRANSACTIONS = "ADMIN_MAIN_ACCOUNT_TRANSACTIONS";
    const ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS = "ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS";
    const ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS = "ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS";
    const ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS = "ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS";
    const FUND_VIRTUAL_ACCOUNT = "FUND_VIRTUAL_ACCOUNT";
    const WITHDRAW_VIRTUAL_ACCOUNT = "WITHDRAW_VIRTUAL_ACCOUNT";
}